all:
  var:
    postgres_port: 5432
  children:
    dev_db_servers:
      vars:
        postgres_user: postgres
        postgres_password: postgres
      hosts: 
        pgsql-db:
          ansible_host: pgsql-db
          dbs:
            - customer_db_1
            - customer_db_2
    
